server:
  port: 8888

eureka:
  instance:
    hostname: registry
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/zhangxd1989/spring-boot-cloud
          uri: https://github.com/yaozi899/springCloudLyf
          search-paths: config-repo
  rabbitmq:
    host: rabbitmq