server:
  port: 7002

spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka.com:7001/eureka
  instance:
    instance-id: gateway.com
    prefer-ip-address: true